sudo: false

language: java

jdk:
  - openjdk8

env:
  - OPENCGA_HOME=$TRAVIS_BUILD_DIR/opencga/opencga-app/build

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -PTravis

script:
  - mvn test -s .travis.settings.xml -PTravis

